### ISSUE TITLE
when i patch youtube this appears

### ISSUE THREAD

**Issue by abdokamel2001** [inotia00/revanced-patches#44] opened 2022-10-30 13:16 UTC
### Type

Error while patching

### Bug description

i tried to patch both youtube music and youtube but youtube doesn't seem to complete installing

### Steps to reproduce

1- download  the latest version (17.42.35)
2- install it in my phone and choose the same version while patching
3- the patches seems to succeed and then it compiles and in the last step it shows me this error

### Relevant log output

```shell
Error: EBUSY: resource busy or locked, unlink '\\?\D:\Documents\Revanced-Builder\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.
```

### Screenshots or videos

![2022-10-30_145627](https://user-images.githubusercontent.com/69877498/198880268-efb5cbf9-b9c8-4b7c-96ab-2ea11d3e2b26.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2022-10-30 13:34
Wrong place to report the issue
Duplicate of https://github.com/inotia00/rvx-builder/issues/7

**Closed by inotia00** 2022-10-30 13:34 UTC
Labels: bug

**Comment by inotia00** [comment] 2022-10-30 14:41
Someone has solved the same issue.
maybe this method can help you
https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651
