### ISSUE TITLE
bug: Video Rewinds Itself When Video Ads Blocked

### ISSUE THREAD

**Issue by anil-al** [inotia00/revanced-patches#18] opened 2022-10-17 22:25 UTC
### Type

Cosmetic

### Bug description

Video rewinds itself 2-3 seconds without any action. It happened in a video a couple of times. Probably about in-between video ads and when they should be shown, normally after watching a advert, we see a little bit of that video videos the advert. When they are removed, it effect continued. It wasn't happening before with Revanced. Maybe because of their new patches about adverts or about your ad patchs.

### Steps to reproduce

Open a relatively long video which normally shows in-between adverts.
Wait until advert time comes in.
See that video is rewound about 2 seconds.

### Relevant log output

```shell
-
```

### Screenshots or videos

-

### Solution

-

### Additional context

https://youtu.be/gtnlGH055TA The video which I faced with this bug.
Patch version: 2.82.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2022-10-18 09:22
> 
unfortunately it doesn't happen on my device
Can you provide a record of when an issue occurs?

**Comment by Spacellary** [comment] 2022-10-18 15:49
I've seen this being reported by many used of Revanced already, so it's a "known issue" but with still being investigated and is apparently related to blocking ads during playback, as the 1-2s replay happens where an Ad would play but was blocked, I experienced that too. I'll assume it's more A/B testing nonsense.

**Comment by anil-al** [comment] 2022-10-18 17:20
> I've seen this being reported by many users of Revanced already, so it's a "known issue" but still being investigated and is apparently related to blocking ads during playback, as the 1-2s replay happens where an Ad would play but was blocked, I experienced that too. I'll assume it's more A/B testing nonsense. But it's hard to catch since it's also hard to predict the random Ads.

What's weird is, it wasn't happening to me previously. It is a bug I newly encountered, so I thought and still think it was because of reworked ad patches.

**Comment by Spacellary** [comment] 2022-10-19 22:52
_Apparently from version patches-2.83.1 and up this is supposed to be fixed, testing here currently with `revanced-patches-v2.82.3` and looking out for the issue, and I'd like ask everyone that has had this bug to do the same we report back after some use if you can._

**Comment by Spacellary** [comment] 2022-10-21 16:38
@anil-al 
Apparently from patches-2.83.1 version and up this is supposed to be fixed.

Have you experienced the bug with the new patches?

**Comment by brgalaxy** [comment] 2022-10-21 16:48
> _Apparently from patches-2.83.1 version and up this is supposed to be fixed._
> Is that confirmed?

I use Revanced Manager on Android, I can't apply these bugfix patches through Revanced Manager or Revanced Builder on Termux, so this bug still happens to me. Is there any way to do this on Android?

**Comment by Spacellary** [comment] 2022-10-21 17:08
> > _Apparently from patches-2.83.1 version and up this is supposed to be fixed._
> > Is that confirmed?
> 
> I use Revanced Manager on Android, I can't apply these bugfix patches through Revanced Manager or Revanced Builder on Termux, so this bug still happens to me. Is there any way to do this on Android?

I use the latest Revanced **Extended** windows builder from the [Releases page](https://github.com/inotia00/rvx-builder/releases/tag/v3.4.15).

I'm currently using Revanced **Extended** but I believe the official manager will download the latest patches version for you when you build again, just download the latest recommended YouTube .apk (not the .apks) from APKMirror. You can try that and see what version of the patches the app has downloaded, I believe you just need to hit the "Update" button on the Patches in the home screen.

**Comment by anil-al** [comment] 2022-10-21 17:52
> @anil-al 
> Apparently from patches-2.83.1 version and up this is supposed to be fixed.
> 
> Have you experienced the bug with the new patches?

Yes, I experienced it with version 2.82.3

**Comment by Spacellary** [comment] 2022-10-21 18:03
> > @anil-al
> > Apparently from patches-2.83.1 version and up this is supposed to be fixed.
> > Have you experienced the bug with the new patches?
> 
> Yes, I experienced it with version 2.82.3

@anil-al Build again, there are new patches. 2.82.3 is outdated. 2.83.3 should be fixed. 👍

**Comment by anil-al** [comment] 2022-10-21 18:04
> > > @anil-al
> > > Apparently from patches-2.83.1 version and up this is supposed to be fixed.
> > > Have you experienced the bug with the new patches?
> > 
> > Yes, I experienced it with version 2.82.3
> 
> @anil-al Build again, there are new patches. 2.82.3 is outdated. 2.83.3 should be fixed. 👍 

Sorry, I meant 2.83.3.

**Comment by Spacellary** [comment] 2022-10-21 18:06
> Sorry, I meant 2.83.3.

Ah, OK xD – Well shiet, I'm keeping an eye out but haven't been noticing it here so far.
The journey continues~

**Comment by inotia00** [comment] 2022-10-22 05:56
> 
Apply the patch released as of today
If the issue is resolved, please close this issue

**Comment by Spacellary** [comment] 2022-10-22 08:56
From me this is the last input I can add unless I experience it happening again for some reason,  but honestly haven't had the issue anymore here so I'll say for me it's fixed, actually since patches 2.83.3 I haven't noticed the issue anymore.

Hopefully this works for you too, anil!

**Closed** 2022-10-22 09:03 UTC
Labels: bug
