### ISSUE TITLE
bug: Reply field is white with Amoled patch, makes it's impossible to see what's being typed.

### ISSUE THREAD

**Issue by Spacellary** [inotia00/revanced-patches#13] opened 2022-10-11 05:41 UTC
### Type

Cosmetic

### Bug description

I have the Theme patch for the AMOLED theme on.

Built YouTube Revanced Extended using `rvx-builder v3.4.15` Windows .exe from the releases page.
```
revanced-integrations-v0.51.0.2
revanced-patches-v2.81.6
revanced-cli-v2.14.1
```

Screenshots of the issue are attached...

Makes it impossible to see what you're typing.

This only happens when replying from the player page, as in with the video opened and you scroll down to the comments.

It does NOT happen if you're replying from the Notifications tab, it actually works as intended from there.
_________________________________________________

Theme: AMOLED.
Xiaomi Redmi Note 11 Global (spes), Xiaomi.eu MIUI 13 - Android 12, no root.
Windows Builder: rvx-builder v3.4.15

![Screenshot_2022-10-09-19-49-16-928_app revanced android youtube](https://user-images.githubusercontent.com/39604793/194783566-22a0ef64-83a2-416e-9631-e11e1131ea3d.png)

![Screenshot_2022-10-09-19-49-02-371_app revanced android youtube](https://user-images.githubusercontent.com/39604793/194783571-edfb0931-7651-4fc3-8058-6ecd00e29e62.png)

### Steps to reproduce

1. Open a video.
2. Go to the comments section.
3. Start typing a reply.
4. Notice the white text field, with white font. Impossible to see the text.

### Relevant log output

```shell
rvx-builder v3.4.15
revanced-integrations-v0.51.0.2
revanced-patches-v2.81.6
revanced-cli-v2.14.1
```

### Screenshots or videos

![msedge_yt9ujMFGpu](https://user-images.githubusercontent.com/39604793/195005779-ae0a689a-2d21-46f7-92d0-7a3e128ac5d3.png)
![msedge_ByZgDiwae0](https://user-images.githubusercontent.com/39604793/195005806-5e70c895-fe00-4fc1-86de-1cf236216a5a.png)
![msedge_4APu3Zbbay](https://user-images.githubusercontent.com/39604793/195005809-106ccafd-f038-4f9f-a38d-76965358d681.png)
![msedge_QcvyEqqhqe](https://user-images.githubusercontent.com/39604793/195005814-8348d940-1208-4982-844b-6a7acd77f204.png)
![msedge_CGFcB4QIzi](https://user-images.githubusercontent.com/39604793/195005820-fdfd41e8-3896-4ed6-8910-f287244ee371.png)

### Additional context

Theme: AMOLED.
Xiaomi Redmi Note 11 Global (spes), Xiaomi.eu MIUI 13 - Android 12, no root.
Windows Builder: rvx-builder v3.4.15

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment] 2022-10-11 14:13
please check if this issue is reproduced on the original YouTube as well

**Comment by Spacellary** [comment] 2022-10-11 17:07
Thanks for your quick response. I'll be honest I didn't even had the original YouTube installed anymore, but after testing it I can confirm that:


**Official YouTube didn't have the issue.**

The reply definitely looks different than what I remembered, so if I had to guess they are definitely messing with something related.

![Screenshot_2022-10-11-13-59-38-489_com google android youtube](https://user-images.githubusercontent.com/39604793/195155772-80cc2af4-ebf2-41bf-8f98-c51a8edf7bf3.jpg)
![Screenshot_2022-10-11-14-01-50-522_com miui home](https://user-images.githubusercontent.com/39604793/195155811-19160740-9f68-4587-93ba-bb39e48c3683.png)

**Comment by inotia00** [comment] 2022-10-12 07:34
thanks. After some more testing, I found that this issue did not reproduce if it applied the `materialyou` patch.
Also, I found out that this issue doesn't happen to all users.
I think I'll need more time to resolve this issue.

**Comment by Spacellary** [comment] 2022-10-12 07:45
I'm assuming the MaterialYou and Amoled patches aren't compatible, or are they? I could give that a try but I wanna keep as much of the app as possible with true black.

**Comment by danieloox** [comment] 2022-10-18 18:39
it's not a app problem. it's a google account problem. on me all is black on another google account.

**Comment by Spacellary** [comment] 2022-10-18 21:09
It's probably like the new like/dislike buttons, being distributed to only a few users at first but if I had to guess it will affect everyone eventually.

**Comment by Spacellary** [comment] 2022-10-22 08:32
@inotia00

Built YouTube with `patches v2.85.1` and the reply field is no longer white, it could be changes to A/B testing or could it be fixed?

@danieloox Can you build Rev. Extended with the latest release and see if it's fixed for you by any chance?


#### How it looks now:
![Screenshot_2022-10-22-05-29-04-644_app rvx android youtube](https://user-images.githubusercontent.com/39604793/197329683-a8de9e61-6028-42cc-933c-9bb93b215546.png)

**Comment by danieloox** [comment] 2022-10-22 08:38
i create new g account and everyrhings is black

**Comment by Spacellary** [comment] 2022-10-22 08:42
> i create new g account and everyrhings is black

What about your old one with the new patches?
Need to find out if the issue is gone or if it's just a change on their side.

Personally I don't like changing accounts, have been using mine for many years so it matters a lot and I imagine people won't just be doing that if the issue spreads.

**Comment by danieloox** [comment] 2022-10-22 08:44
i not update at the moment. i can try it :)

**Comment by danieloox** [comment] 2022-10-22 09:03
same on newest. on new account is good

**Comment by danieloox** [comment] 2022-10-22 09:15
this is happening on account. Patches have nothing to do with it

**Comment by Spacellary** [comment] 2022-10-22 19:42
> this is happening on account. Patches have nothing to do with it

They will have to, this needs to be fixed. Account or not the fix needs to be from the patches.
Good to know then, thanks for testing again.

**Comment by inotia00** [comment] 2022-10-30 14:02
YouTube v17.42.35
revanced-patches v2.99.0
new layout

When tested in this environment, does this still reproduce this issue?

**Comment by Spacellary** [comment] 2022-10-30 14:06
> YouTube v17.42.35
> revanced-patches v2.99.0
> new layout
> 
> When tested in this environment, does this still reproduce this issue?

I'm unable to build this version currently due to issue https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217 and none of my accounts have received the new layout as of right now, I tried 5 different accounts in YouTube app version 17.41.37 with patches version 2.85.2.

**Comment by Spacellary** [comment] 2022-10-30 15:24
> YouTube v17.42.35
> revanced-patches v2.99.0

Alright @inotia00 here's how it is now, still with the Old Layout... But things seem to have changed somehow again.

![Screenshot_2022-10-30-12-17-17-709_app.rvx.android.youtube.jpg](https://user-images.githubusercontent.com/39604793/198886738-f6a677e1-ea73-4210-93a2-a69f3516e078.jpg)
![Screenshot_2022-10-30-12-17-32-063_app.rvx.android.youtube.jpg](https://user-images.githubusercontent.com/39604793/198886751-6d4b7da7-56a7-40fb-ba64-323e8d488e3a.jpg)

This is looking bad again, it's now white again even for me. It's now looking how it does in Official Revanced. The screenshots are of the MaterialYou theme.

**Comment by Spacellary** [comment] 2022-10-30 15:29
#### This is the AMOLED theme... Still like before.

![Screenshot_2022-10-30-12-26-58-063_app.rvx.android.youtube.jpg](https://user-images.githubusercontent.com/39604793/198887012-dce7fd66-1b94-43f1-8dcd-9f3d6ce211c3.jpg)
![Screenshot_2022-10-30-12-27-08-878_app.rvx.android.youtube.jpg](https://user-images.githubusercontent.com/39604793/198887031-63369e94-004c-4b9c-bd4f-48a5b54421c0.jpg)

    YT 17.42.35
    Patches 2.99.0

**Comment by inotia00** [comment] 2022-10-30 15:37
umm.. does the ReVanced official have the same issue?

**Comment by Spacellary** [comment] 2022-10-30 15:38
> umm.. does the ReVanced official have the same issue?

I'll do a fresh Build on recommended and report back.

**Comment by Spacellary** [comment] 2022-10-30 15:52
Official `ReVanced-YouTube-v17.41.37-cli_v2.14.0-patches_v2.100.0` results:

#### No Theme Patch:


#### With Theme Patch:

**Comment by Spacellary** [comment] 2022-10-31 05:03
So far only get the old layout (maybe for the best, the new one bothers me a lot in some areas from what I have seen online) but I'll be reporting back if/when I get the new layout as it may not be an issue there.

**Comment by Spacellary** [comment] 2022-11-01 00:54
@inotia00 - **New layout rolled out. Amoled theme for me now:**
<br>
![amoled](https://i.postimg.cc/2yjggLmD/yt.jpg)
<br>
![amoled](https://i.postimg.cc/xTCWRmtG/ytt.jpg)

**Comment by inotia00** [comment] 2022-11-11 09:08
Finally I had this issue on my device as well
(probably, this looks like an A/B test by YouTube)

I'm currently trying to fix it, and if a release comes up today or tomorrow, please test to see if the issue is resolved.

**Comment by Spacellary** [comment] 2022-11-11 10:29
Of course, I'm always looking out for updates on this. Will do!

**Comment by inotia00** [comment] 2022-11-11 14:35
YouTube v17.43.37
revanced-patches v2.106.1

When tested in this environment, does this still reproduce this issue?

**Comment by Spacellary** [comment] 2022-11-11 15:01
#### @inotia00 this is what it looks like here now. Some progress! But still...
<br>

![Screenshot_2022-11-11-12-00-02-989_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201366936-cde69838-bb97-4ab8-a67c-ac6004abbe36.jpg)

**Comment by inotia00** [comment] 2022-11-11 15:20
That's what I intended

Because.. when YouTube designed the comments input section in the new layout, the background color was designed to be white in the dark theme.. (result of analyzing the code of YouTube)

So, I adjusted the contrast and changed it to be readable.

At least the comments you're writing will be readable

**Comment by inotia00** [comment] 2022-11-11 15:21
btw, comment filter color still looks dark

**Comment by Spacellary** [comment] 2022-11-11 15:26
This is how it was up to patches 2.102 with Amoled btw: https://github.com/inotia00/revanced-patches/issues/13#issuecomment-1297867892

**Comment by Spacellary** [comment] 2022-11-11 15:29
> So, I adjusted the contrast and changed it to be readable.

Wait so it's not possible to make it actually black anymore? :'|

**Comment by inotia00** [comment] 2022-11-11 15:32
> 
nop, amoled patch is still available
![ReVanced_v2 106 1](https://user-images.githubusercontent.com/108592928/201372835-50338e39-c10f-4870-9c05-23b858180528.png)

**Comment by Spacellary** [comment] 2022-11-11 15:35
Ah, I see so it's still only me and the A/B. Weird stuff. It really does look different!

**Comment by Spacellary** [comment] 2022-11-11 15:40
#### Alt account with Amoled on latest Patches:

![Screenshot_2022-11-11-12-38-57-052_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201374401-1c2f99c0-cfb0-43d5-8747-1e7d0eaf3c1a.jpg)
![Screenshot_2022-11-11-12-39-04-330_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201374409-4496781f-6e7a-4d51-9617-0dec1e8c63b9.jpg)
![Screenshot_2022-11-11-12-39-15-364_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201374411-70843072-752b-4509-9215-662c4c85d0a3.jpg)

**Comment by inotia00** [comment] 2022-11-11 15:44
Would you like to test the tablet layout once on?

**Comment by Spacellary** [comment] 2022-11-11 15:51
> When selecting text it does look like a big black box pops up, it's tall and obstructs the field.
 It happens in my alt accounts, with tablet layout enabled or not.

**Comment by Spacellary** [comment] 2022-11-11 15:52
On my A/B affected account it looks like https://github.com/inotia00/revanced-patches/issues/13#issuecomment-1311794966, same.

**Comment by inotia00** [comment] 2022-11-12 17:00
YouTube v17.44.34
revanced-patches v2.106.5

When tested in this environment, does this still reproduce this issue?

**Comment by Spacellary** [comment] 2022-11-12 18:15
YouTube v17.44.34
revanced-patches v2.106.5
<br>

![Screenshot_2022-11-12-15-11-34-885_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201488765-3ea31f4c-25ad-45aa-abff-f6b39aee8bbd.jpg)
<br>

![Screenshot_2022-11-12-15-14-27-851_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201488767-1ae81705-c333-4937-8058-90d159e3faae.jpg)

**Comment by Spacellary** [comment] 2022-11-12 18:28
YouTube v17.44.34
revanced-patches v2.106.5
#### A/B affected account with Tablet Layout: Enabled
<br>

![Screenshot_2022-11-12-15-25-59-994_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201489226-6c909486-0aad-47df-8821-99bb0816886b.jpg)
![Screenshot_2022-11-12-15-26-06-591_app rvx android youtube](https://user-images.githubusercontent.com/39604793/201489229-61010871-01e6-4467-9f27-4beb1689c87f.jpg)

**Comment by inotia00** [comment] 2022-11-12 18:28
It looks like a new issue

anyway, this issue page has been solved, so I'll close it

Please open a separate page for that issue.

**Closed by inotia00** 2022-11-12 18:28 UTC
Labels: bug
